### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by dzsquared** [conda-forge/go-sqlcmd-feedstock#2]
### Comment:

Hi! I'm from the go-sqlcmd project and this is very cool to see.  I was curious if you could share how you or others are using go-sqlcmd when it's installed through conda.

**Comment by dhirschfeld** [comment]
Hi @dzsquared :wave:
We use `mamba` to install all of our analytics (Python/R) code and insofar as possible I try to install all my tooling using `mamba` as well.

It's easier keeping things up to date if you only have to worry about using one package manager - e.g. I can tell my team to just install `stanwell-devops` and know they'll have everything they need for deploying our infrastructure:
```yaml
outputs:
  - name: stanwell-devops
    requirements:
      run:
        - go-sqlcmd >=0.7.0
        - terraform >=1.1.4
        - terragrunt >=0.36.0
        - kubernetes >=1.23.3,<1.25
        - kubelogin >=0.0.10
        - kubernetes-helm >=3.8.0
        - minikube >=1.24.0
        - packer >=1.7.9
```
We're using `go-sqlcmd` as part of our automatic deployment of Azure SQL databases using `terraform`. When a new database is provisioned, AAD groups for access are also provisioned. We then use `go-sqlcmd` (via null resources) to create the corresponding users in the database and assign them corresponsing roles (via `sp_addrolemember`).

Anyway, I didn't have any luck connecting to our Azure SQL databases using `sqlcmd` so fortunately I found `go-sqlcmd` which Just Worked! :tada: It's also hugely easier (and licensing is clearer) deploying `go-sqlcmd` in our CI/CD containers that it would have been with `sqlcmd`.

### Note:
I install tooling into my base environment which is on my `PATH` (which may or may not be questionable practice). [`condax`](https://github.com/mariusvniekerk/condax) is a tool specifically designed to install applications in isolated environments.
